### ISSUE TITLE
Why aren't you testing against spring-data-eclipse-store?

### ISSUE THREAD

**Issue by LiveNathan** [xdev-software/spring-data-eclipse-store#144]
https://github.com/xdev-software/spring-data-eclipse-store/blob/991d3755a59ce66eff82071fbcf602cbd3ccf3df/spring-data-eclipse-store/pom.xml#L136

I'm confused. Why aren't you testing against spring-data-eclipse-store?

**Comment by LiveNathan** [comment]
The context is that I'm trying to write my first repository test using spring-data-eclipse-store by following your example, but the very first annotation `@DefaultTestAnnotations` comes from `software.xdev.spring.data.eclipse.store.integration.shared.DefaultTestAnnotations` which doesn't come from the spring-data-eclipse-store dependency. So I started looking at the pom file for your example test and it doesn't even include this dependency so I got confused.

**Comment by JohannesRabauer** [comment]
The [here](https://github.com/xdev-software/spring-data-eclipse-store/issues/141#issuecomment-2283127531) mentioned  [SimpleSingleTest](https://github.com/xdev-software/spring-data-eclipse-store/blob/991d3755a59ce66eff82071fbcf602cbd3ccf3df/spring-data-eclipse-store/src/test/java/software/xdev/spring/data/eclipse/store/integration/shared/tests/SimpleSingleTest.java#L61) **is part of the spring-data-eclipse-store-Module**. That's why we don't need any dependency to it.

So we have multiple places and modules where we implemented Tests. The first one you mentioned [here](https://github.com/xdev-software/spring-data-eclipse-store/issues/141#issue-2459266587) is in the [spring-data-eclipse-store-demo](https://github.com/xdev-software/spring-data-eclipse-store/tree/develop/spring-data-eclipse-store-demo) module. The [SimpleSingleTest](https://github.com/xdev-software/spring-data-eclipse-store/blob/991d3755a59ce66eff82071fbcf602cbd3ccf3df/spring-data-eclipse-store/src/test/java/software/xdev/spring/data/eclipse/store/integration/shared/tests/SimpleSingleTest.java#L61)-Test in in the [spring-data-eclipse-store-Module](https://github.com/xdev-software/spring-data-eclipse-store/tree/develop/spring-data-eclipse-store) itself.
Of course the test classes are always in the /src/test/ Path.

I hope that helps.

**Comment by LiveNathan** [comment]
Thanks Johannes. Somehow I am still confused. Which one do I need to look at if I want to write a repository test against spring-data-eclipse-store?

The [SimpleDemoApplicationTest](https://github.com/xdev-software/spring-data-eclipse-store/blob/develop/spring-data-eclipse-store-demo/src/test/java/software/xdev/spring/data/eclipse/store/demo/simple/SimpleDemoApplicationTest.java) does do much so I don't think that's the one. [SimpleSingleTest](https://github.com/xdev-software/spring-data-eclipse-store/blob/991d3755a59ce66eff82071fbcf602cbd3ccf3df/spring-data-eclipse-store/src/test/java/software/xdev/spring/data/eclipse/store/integration/shared/tests/SimpleSingleTest.java#L61) looks like exactly what I need, but it starts off with `@DefaultTestAnnotations`, for which I don't have the required dependency. So, I'm not sure what you're recommending.

**Comment by JohannesRabauer** [comment]
The `@DefaultTestAnnotations`-Class is one package above the [SimpleSingleTest.java](https://github.com/xdev-software/spring-data-eclipse-store/blob/991d3755a59ce66eff82071fbcf602cbd3ccf3df/spring-data-eclipse-store/src/test/java/software/xdev/spring/data/eclipse/store/integration/shared/tests/SimpleSingleTest.java#L61): [DefaultTestAnnotations.java](https://github.com/xdev-software/spring-data-eclipse-store/blob/991d3755a59ce66eff82071fbcf602cbd3ccf3df/spring-data-eclipse-store/src/test/java/software/xdev/spring/data/eclipse/store/integration/shared/DefaultTestAnnotations.java)

So if you checked out the complete [spring-data-eclipse-store-Repository](https://github.com/xdev-software/spring-data-eclipse-store) you have all the needed classes.

**Comment by LiveNathan** [comment]
Ah, ok, that makes more sense. Thanks for explaining. I still have some issues to work out before I get my test working, but I should mark this issue as closed.
